#!/bin/bash

source ./config

# Clean up previous run
function clean() {
  set +x
  echo Cleaning...
  ibmcloud cr namespace-rm "${ICR_NS}" -f > /dev/null 2>&1 || true
  ibmcloud ce app delete -n assistant-proxy -f --wto=0 > /dev/null 2>&1 || true
  ibmcloud ce secret delete -n wa-api-key -f > /dev/null 2>&1 || true
  ibmcloud ce configmap delete -n wa-url -f > /dev/null 2>&1 || true
  ibmcloud ce configmap delete -n wa-version -f > /dev/null 2>&1 || true
  ibmcloud ce configmap delete -n assistant-info -f > /dev/null 2>&1 || true
  ibmcloud iam api-key-delete s2i-sample -f > /dev/null 2>&1 || true
  ibmcloud ce registry delete -n icr -f > /dev/null 2>&1 || true
  ibmcloud ce buildrun delete -n myrun -f > /dev/null 2>&1 || true
  ibmcloud ce build delete -n mybuild -f > /dev/null 2>&1 || true
  rm -f out || true
}

# Define our ICR Namespace env var for later use
ID=$(ibmcloud account show | grep "Account ID:" | sed "s/^.*:  *//")
ICR_NS=s2i-${ID:0:25}
IMAGE_NAME=us.icr.io/${ICR_NS}/tririga-assistant-proxy

[[ "$1" == "clean" ]] && clean && exit 0

set -ex

# Create an ICR namespace to hold our new image
ibmcloud cr namespace-add $ICR_NS

# Create an apikey, put it in a registry secret. Used to push/pull image to ICR
ibmcloud iam api-key-create s2i-sample | \
  grep "API Key" | sed 's/^.*Key  *//' | \
  xargs ibmcloud ce registry create -n icr -s us.icr.io -u iamapikey -p

# Define the build of this dir in this github repo
ibmcloud ce build create -n mybuild -i "${IMAGE_NAME}" --rs icr \
  --source https://github.com/IBM/tririga-assistant-proxy --strategy buildpacks

# Now kick off the build itself
ibmcloud ce buildrun submit -n myrun --build mybuild

# Wait for it to finish
while true ; do
  ibmcloud ce buildrun get -n myrun > out
  grep Succeeded out && break
  grep "exited with" out && cat out && exit 1
  sleep 10
done

# Create configmaps to be used as env vars by the app - config maps aren't encrypted at rest
ibmcloud ce configmap create --name wa-url --from-literal WA_URL=${WA_URL}
ibmcloud ce configmap create --name wa-version --from-literal WA_VERSION=${WA_VERSION}
ibmcloud ce configmap create --name assistant-info --from-literal ASSISTANT_INFO="${ASSISTANT_INFO}"

# Create secrets for confidential env vars - secrets are encrypted at rest
ibmcloud ce secret create --name wa-api-key --from-literal WA_API_KEY=${WA_API_KEY}

# Test the image we just built - deploy an app and 'curl' it
ibmcloud ce app create -n assistant-proxy --image "${IMAGE_NAME}" --rs icr \
  --env-from-configmap wa-url --env-from-configmap wa-version \
  --env-from-configmap assistant-info --env-from-secret wa-api-key

URL=$(ibmcloud ce app get -n assistant-proxy -o jsonpath={.status.url})
curl -Ls "${URL}" | tee out

if ! grep "Cannot GET"  out > /dev/null ; then
  echo "Missing expected outout"
  exit 1
fi

# Clean
#clean