#!/bin/bash

# Clean up previous run
function clean() {
  set +x
  echo Cleaning...
  ibmcloud cr namespace-rm "${ICR_NS}" -f > /dev/null 2>&1 || true
  ibmcloud ce app delete -n assistant-proxy -f --wto=0 > /dev/null 2>&1 || true
  ibmcloud iam api-key-delete s2i-sample -f > /dev/null 2>&1 || true
  ibmcloud ce registry delete -n icr -f > /dev/null 2>&1 || true
  ibmcloud ce buildrun delete -n myrun -f > /dev/null 2>&1 || true
  ibmcloud ce build delete -n mybuild -f > /dev/null 2>&1 || true
  rm -f out || true
}

# Define our ICR Namespace env var for later use
ID=$(ibmcloud account show | grep "Account ID:" | sed "s/^.*:  *//")
ICR_NS=s2i-${ID:0:25}
IMAGE_NAME=us.icr.io/${ICR_NS}/tririga-assistant-proxy

#clean
[[ "$1" == "clean" ]] && exit 0

set -ex

# Create an ICR namespace to hold our new image
ibmcloud cr namespace-add $ICR_NS

# Create an apikey, put it in a registry secret. Used to push/pull image to ICR
ibmcloud iam api-key-create s2i-sample | \
  grep "API Key" | sed 's/^.*Key  *//' | \
  xargs ibmcloud ce registry create -n icr -s us.icr.io -u iamapikey -p

# Define the build of this dir in this github repo
ibmcloud ce build create -n mybuild -i "${IMAGE_NAME}" --rs icr \
  --source https://github.com/IBM/tririga-assistant-proxy --strategy buildpacks

# Now kick off the build itself
ibmcloud ce buildrun submit -n myrun --build mybuild

# Wait for it to finish
while true ; do
  ibmcloud ce buildrun get -n myrun > out
  grep Succeeded out && break
  grep "exited with" out && cat out && exit 1
  sleep 10
done

# Test the image we just built - deploy an app and 'curl' it
ibmcloud ce app create -n assistant-proxy --image "${IMAGE_NAME}" --rs icr
URL=$(ibmcloud ce app get -n assistant-proxy -o jsonpath={.status.url})
curl -Ls "${URL}" | tee out

if ! grep "I was built"  out > /dev/null ; then
  echo "Missing expected outout"
  exit 1
fi

# Clean
#clean